// <auto-generated />
using System;
using Billing.WebApi.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Billing.WebApi.Migrations
{
    [DbContext(typeof(BillingContext))]
    partial class BillingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.ComponentDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("QuantityType")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.ToTable("Component");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.CustomerDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Phone" }, "Customer_phone_key")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.GoodComponentLinkDbo", b =>
                {
                    b.Property<Guid>("GoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("good_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("GoodId", "ComponentId")
                        .HasName("GoodComponent_pkey");

                    b.HasIndex("ComponentId");

                    b.ToTable("GoodComponent");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.GoodDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("QuantityType")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.OrderDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("creation_date");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_status");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.OrderGoodLinkDbo", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("GoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("good_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "GoodId")
                        .HasName("OrderGood_pkey");

                    b.HasIndex("GoodId");

                    b.ToTable("OrderGood");
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.GoodComponentLinkDbo", b =>
                {
                    b.HasOne("Billing.WebApi.Repositories.Models.ComponentDbo", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .HasConstraintName("GoodComponent_component_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.WebApi.Repositories.Models.GoodDbo", null)
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .HasConstraintName("GoodComponents_goods_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.OrderDbo", b =>
                {
                    b.HasOne("Billing.WebApi.Repositories.Models.CustomerDbo", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("Order_customer_id_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.WebApi.Repositories.Models.OrderGoodLinkDbo", b =>
                {
                    b.HasOne("Billing.WebApi.Repositories.Models.GoodDbo", null)
                        .WithMany()
                        .HasForeignKey("GoodId")
                        .HasConstraintName("OrderGood_good_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.WebApi.Repositories.Models.OrderDbo", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .HasConstraintName("OrderGood_order_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
